### ISSUE TITLE
@PDF-HIDDEN

### ISSUE THREAD

**Issue by ghost** [grezniczek/redcap_pdf_actiontags#3]
Dear Grezniczek,

We have just install your external module redcap_pdf_actiontags to hidden a variable to be print in a pdf (REDCap version is 8.11.9). We add the following code to Action Tags:

@DEFAULT='[user-dag-id]' @PDF-HIDDEN="blank"

...and we get the follwing error message when we try to get the pdf:

Error message: Uncaught Error: Call to undefined function RUB\PDFActionTagsExternalModule\apache_setenv() in /var/www/vhosts/idibell.cat/redcap.idibell.cat/modules/redcap_pdf_actiontags_v1.1.2/pdf.php:18 Stack trace: #0 /var/www/vhosts/idibell.cat/redcap.idibell.cat/redcap_v8.11.9/ExternalModules/index.php(102): require_once() #1 {main} thrown 
File: /var/www/vhosts/idibell.cat/redcap.idibell.cat/modules/redcap_pdf_actiontags_v1.1.2/pdf.php 
Line: 18

Any clue?

Thank you very much in advance,

Cristian Tebé-

**Comment by grezniczek** [comment]
Sorry for the delay here .. for some reason I did not get an email from GitHub or missed it. 
This was reported today on the community pages. The fix is out in 1.1.3, which I am just now also submitting to the EM Repo.
